[package]
name = "bsp"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
glam = "0.28.0"
nom = "7.1.3"
wad = { path = "../wad" }
byte_writer = { path = "../byte_writer" }
common = { path = "../common" }
thiserror = "2.0.12"
